# Generated by Django 6.1.1 on 2026-09-17 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('predicted_label', models.CharField(help_text='The label originally generated by the ML model', max_length=20)),
                ('actual_label', models.CharField(choices=[('Real', 'Real News (False Positive)'), ('Fake', 'Fake News (False Negative)'), ('Uncertain', 'Uncertain / Satirical Ambiguity')], help_text='The correct ground truth label asserted by the researcher', max_length=20)),
                ('comment', models.TextField(help_text='Detailed justification, fact-checker citations, or wire URLs')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Investigation'), ('approved', 'Approved / Verified Error'), ('rejected', 'Rejected / Invalid Flag')], db_index=True, default='pending', help_text='Review status in the editorial audit pipeline', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when administrator evaluated this report', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes or retraining dataset tags')),
                ('prediction', models.ForeignKey(help_text='The specific prediction record being contested', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='predictions.prediction')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who reviewed this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Researcher who submitted this discrepancy report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discrepancy Feedback',
                'verbose_name_plural': 'Discrepancy Feedback Reports',
                'db_table': 'verifai_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='verifai_fee_status_314280_idx'), models.Index(fields=['user', '-created_at'], name='verifai_fee_user_id_9c082a_idx')],
            },
        ),
    ]
