from django.db import models
from django.conf import settings
from django.utils import timezone
from apps.core.models import TimeStampedUUIDModel


class Feedback(TimeStampedUUIDModel):
    """
    Human-in-the-loop feedback report submitted by authenticated researchers
    to flag model misclassifications and provide ground-truth provenance.
    """
    STATUS_CHOICES = (
        ('pending', 'Pending Review'),
        ('under_review', 'Under Investigation'),
        ('approved', 'Approved / Verified Error'),
        ('rejected', 'Rejected / Invalid Flag'),
    )

    LABEL_CHOICES = (
        ('Real', 'Real News (False Positive)'),
        ('Fake', 'Fake News (False Negative)'),
        ('Uncertain', 'Uncertain / Satirical Ambiguity'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='submitted_feedback',
        db_index=True,
        help_text="Researcher who submitted this discrepancy report"
    )

    prediction = models.ForeignKey(
        'predictions.Prediction',
        on_delete=models.CASCADE,
        related_name='feedback_reports',
        db_index=True,
        help_text="The specific prediction record being contested"
    )

    predicted_label = models.CharField(
        max_length=20,
        help_text="The label originally generated by the ML model"
    )

    actual_label = models.CharField(
        max_length=20,
        choices=LABEL_CHOICES,
        help_text="The correct ground truth label asserted by the researcher"
    )

    comment = models.TextField(
        help_text="Detailed justification, fact-checker citations, or wire URLs"
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending',
        db_index=True,
        help_text="Review status in the editorial audit pipeline"
    )

    reviewed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Timestamp when administrator evaluated this report"
    )

    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reviewed_feedbacks',
        help_text="Staff member who reviewed this feedback"
    )

    admin_notes = models.TextField(
        blank=True,
        help_text="Internal notes or retraining dataset tags"
    )

    class Meta:
        db_table = 'verifai_feedback'
        verbose_name = 'Discrepancy Feedback'
        verbose_name_plural = 'Discrepancy Feedback Reports'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['status', '-created_at']),
            models.Index(fields=['user', '-created_at']),
        ]

    def __str__(self):
        return f"Feedback on {self.prediction_id} [{self.status}]: Predicted {self.predicted_label} vs Actual {self.actual_label}"
