# Generated by Django 6.1.1 on 2026-09-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='Member', help_text='User role (e.g. Member, Analyst, Admin)', max_length=50),
        ),
    ]
